apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  description: Projeto Terraform para AWS OpenSearch
  tags:
    - terraform
    - aws
    - opensearch
spec:
  type: infrastructure
  lifecycle: experimental
  owner: ${{ values.owner }}