apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Projeto Terraform para AWS OpenSearch
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}